update generate_query_body to allow for optional rels (with two mandatory classes)
GSK-Biostatistics/tab2neo pull request #13
Opened 2023-01-09 17:52 UTC by WillMcDGSK

@paltusplintus or @JonathanDeacon Please review!

This PR is for [this PBI bugfix](https://dev.azure.com/DevOps-RD/Clinical%20Linked%20Data%20Experiments/_sprints/taskboard/Clinical%20Linked%20Data%20Experiments%20Team/Clinical%20Linked%20Data%20Experiments/Sprint%209.5?workitem=953428). I fixed the issue where if you have a relationships that has a mandatory class on either end of a relationship, the relationship would not then be counted as optional. This happens in the case in the PBI as the final relationship EX->DTC has two classes that are mandatory from the relationships defined before it. 

This update should not affect the way queries are generate already, but please check to make sure optional matches are still split out as intended!

This PR also has a cldnb PR to go along with it, but they do not depend on each other.

2023-01-10 15:41 UTC, JonathanDeacon requested changes
Code looks good and seems to work as intended, however the qb unit tests will need updating to match the new format:

<img width="179" alt="image" src="https://user-images.githubusercontent.com/96542374/211595802-89147a94-1e3b-47a6-877f-8bd84c985801.png">

2023-01-11 10:43 UTC, WillMcDGSK commented
Ready for review again!

2023-01-12 13:57 UTC, JonathanDeacon approved these changes
Changes look good!

2023-01-12 13:57 UTC, merged

2023-01-16 06:43 UTC, paltusplintus commented
@WillMcDGSK 
This PR seemed to have triggered an error with adam_data_provider - see PBI https://dev.azure.com/DevOps-RD/Clinical%20Linked%20Data%20Experiments/_sprints/taskboard/Clinical%20Linked%20Data%20Experiments%20Team/Clinical%20Linked%20Data%20Experiments/Sprint%209.5